<?php

/**
 * @file
 * Contains facebook_pixel.module.
 */

use Drupal\facebook_pixel\PixelScriptBuilder;
require_once 'PixelScriptBuilder.php';

/**
 * Implements hook_page_attachments().
 */
function facebook_pixel_page_attachments(array &$page) {
    // Return if user is admin
    $roles = \Drupal::currentUser()->getRoles();
    if (is_array($roles) && in_array("administrator", $roles)) {
        return;
    }

    $config = \Drupal::config('facebook_pixel.settings');
    $pixel_id = $config->get('pixel_id');

    $pixel = new PixelScriptBuilder($pixel_id);
    $pixel_script_code = $pixel->getPixelScriptCode();
    $pixel_noscript_code = $pixel->getPixelNoscriptCode();

    // Inject inline script code to head
    $page['#attached']['html_head'][] = [
        [
            '#tag' => 'script',
            '#value' => $pixel_script_code
        ],
        'facebook_pixel_script_code'
    ];

    $page['#attached']['html_head'][] = [
        [
            '#tag' => 'noscript',
            '#value' => $pixel_noscript_code
        ],
        'facebook_pixel_noscript_code'
    ];
}
